#!/bin/bash
#Colores
g="${b}\033[1;30m"
b="\033[0m"
b1="$b\033[1;37m"
r="${b}\033[1;31m"
r1="${b}\033[31m"
A="${b}\033[1;34m"
A1="${b}\033[34m"
ac="${b}\e[1;36m"
ac1="${b}\e[36m"
v="${b}\033[1;32m"
v1="${b}\033[32m"
m="$b\033[1;35m"
m1="$b\033[35m"
a="$b\033[1;33m"
a1="$b\033[33m"
cy="$b\033[38;2;23;147;209m"
trap Adios INT
Adios() {
		sleep 0.2
		echo -e "\n${v}\n[$b1+$v]$b1 Finished\n$v[$b1+$v]$b1 Created by Anonymous Zpt\n$v[$b1+$v]$b1 Gracias por usar mi herramienta\n$v[$b1+$v]$b1 servicio de ayuda https://t.me/Anonymous_Zpt$b\n"
		sleep 0.0
		exit
	}
case $(command -v nano) in
"")
case $(ping -c 1 -q www.google.com >&/dev/null; echo $?) in
0)
;;
*)
echo -e "\n$r[-]$b1 T-banner5:$r No Hay Conexion A Internet.\n$b"
exit
esac
clear
echo -e "$r\n▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄ $A[$b+$A]${b}$b1 Creador:    $a Anonymous Zpt$r\n████▌▄▌▄▐▐▌█████ $A[$b+$A]${b}$b1 Herramienta:$a T-banner5$r\n████▌▄▌▄▐▐▌▀████ $A[$b+$A]${b}$b1 Github:     $a https://github.com/Anonymous-Zpt$r\n▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀ $A[$b+$A]${b}$b1 Youtube:    $a http://www.youtube.com/c/AnonymousZpt$r\n$b"
echo
sleep 0.5
printf "${v}Instalando Dependencias..!$b\n"
pkg install -y nano
source 'T-banner'
exit
esac
b1() {
clear
echo -e $v' _______  __                                       ______
|_     _||  |--..---.-..-----..-----..-----..----.|    __|
  |   |  |  _  ||  _  ||     ||     ||  -__||   _||__    |
  |___|  |_____||___._||__|__||__|__||_____||__|  |______|
'$b
printf "$A[$b1+$A]${b1} Creador:$a     Anonymous Zpt\n"
printf "$A[$b1+$A]${b1} Herramienta:$a T-banner5\n"
printf "$A[$b1+$A]${b1} GitHub:$a      https://github.com/Anonymous-Zpt\n"
printf "$A[$b1+$A]${b1} YouTube:$a     http://www.youtube.com/c/AnonymousZpt$b\n\n"
}
banner() {
b1
echo -e "${v}Pega el banner y cuando termines das 'CTRL X', 'Y' y 'Enter'$b"
read -p "Presione enter para continuar: "
nano .Banner
b1
echo -ne "${v}Defaul 0
Cuantas veces quiere que titile: $b"
read veces
}
color() {
b1
sleep 0.5
echo -e "${v}Elige un color para el banner:$b"
echo -e " $A[${b1}01$A]${b} Blanco
 $A[${b1}02$A]${b1} Blanco2
 $A[${b1}03$A]${r} Rojo
 $A[${b1}04$A]${r1} Rojo2
 $A[${b1}05$A]${A} Azul
 $A[${b1}06$A]${A1} Azul2
 $A[${b1}07$A]${ac} Azul3
 $A[${b1}08$A]${ac1} Azul4
 $A[${b1}09$A]${v} Verde
 $A[${b1}10$A]${v1} Verde2
 $A[${b1}11$A]${m} Morado
 $A[${b1}12$A]${m1} Morado2
 $A[${b1}13$A]${a} Amarillo
 $A[${b1}14$A]${a1} Amarillo2
 $A[${b1}15$A]${g} Gris
$b"
printf " $A[$b1+$A]$v T-banner:$b "
read color
case $color in
01|1)
Color=$b;;
02|2)
Color=$b1;;
03|3)
Color=$r;;
04|4)
Color=$r1;;
05|5)
Color=$A;;
06|6)
Color=$A1;;
07|7)
Color=$ac;;
08|8)
Color=$ac1;;
09|9)
Color=$v;;
10)
Color=$v1;;
11)
Color=$m;;
12)
Color=$m1;;
13)
Color=$a;;
14)
Color=$a1;;
15)
Color=$g;;
*)
echo -e " $r[-]$b1 Color invalido..!$b"
sleep 0.5
color
esac
}
banner
color
mv .Banner Banner &>> /dev/null
if [ -e $PREFIX/etc/motd ]; then
rm $PREFIX/etc/motd
fi
if [ -e $PREFIX/etc/bash.bashrc ]; then
rm $PREFIX/etc/bash.bashrc
echo "if [ -x /data/data/com.termux/files/usr/libexec/termux/command-not-found ]; then" >> $PREFIX/etc/bash.bashrc
echo "  command_not_found_handle() {" >> $PREFIX/etc/bash.bashrc
echo '          /data/data/com.termux/files/usr/libexec/termux/command-not-found "$1"' >> $PREFIX/etc/bash.bashrc
echo "  }" >> $PREFIX/etc/bash.bashrc
echo "fi" >> $PREFIX/etc/bash.bashrc
echo >> $PREFIX/etc/bash.bashrc
echo "PS1='\\$ '" >> $PREFIX/etc/bash.bashrc
case $veces in
"")
echo -e "echo -e '${Color}'" >> $PREFIX/etc/bash.bashrc
echo -e "clear;cat ~/T-banner5/Banner" >> $PREFIX/etc/bash.bashrc
echo -e 'echo -e "\033[0m"' >> $PREFIX/etc/bash.bashrc
;;
*)
nn=1
echo -e "echo -e '${Color}'" >> $PREFIX/etc/bash.bashrc
while [ $nn -le $veces ]; do
nn=$(($nn + 1))
echo -e "clear;cat ~/T-banner5/Banner" >> $PREFIX/etc/bash.bashrc
done
echo -e 'echo -e "\033[0m"' >> $PREFIX/etc/bash.bashrc
sleep 0.5
esac
fi
b1
echo -ne "${v}Ver Banner(y/n):$b "
read yaa
case $yaa in
y|Y)
case $veces in
"")
echo -e "${Color}"
clear;cat ~/T-banner5/Banner
echo -e "\033[0m"
;;
*)
nn=1
while [ $nn -le $veces ]; do
nn=$(($nn + 1))
echo -e "${Color}"
clear;cat ~/T-banner5/Banner
echo -e "\033[0m"
done
esac
;;
n|N)
echo -e "$b"
exit
;;
*)
echo -e "$b"
exit
esac
